name: homefe
description: A special Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.7 <4.0.0'
  flutter: '>=3.38.6'

dependencies:
  flutter:
    sdk: flutter
  dio: 5.9.0
  flutter_bloc: 9.1.1
  rss_dart: 1.0.14
  html: 0.15.6
  intl: 0.20.2
  go_router: 15.1.1
  url_launcher: 6.3.1
  timeago: 3.7.1
  cached_network_image: 3.4.1
  json_annotation: 4.9.0
  collection: 1.19.1
  logger: 2.6.2
  two_dimensional_scrollables: 0.3.8
  flutter_svg: 2.2.1
  window_manager: 0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
  assets:
    - assets/thumbnails/random-source.svg
    - assets/thumbnails/phoronix.svg
    - assets/thumbnails/slashdot.svg
    - assets/thumbnails/techcrunch.svg
    - assets/thumbnails/dpreview.svg
    - assets/thumbnails/toms-hardware.svg
    - assets/thumbnails/ars-technica.svg
    - assets/thumbnails/hacker-news.svg
